### ISSUE TITLE
Missing functions to plot CPM results

### ISSUE THREAD

**Issue by tobac** [AlexChristensen/NetworkToolbox#4]
I'm using NetworkToolbox 1.4.0 on R 4.0.2 on Arch Linux. While I'm able to use cpmIV(() on the "restOpen" dataset, there is no cpmPlot() as mentioned in the man page. Looking at your GitHub repo, you seem to have added plot.cpm() which is also not available (yet?). Long story short: Right now I'm unable to plot my CPM results independently (independent of cpmIV, that is, which produces a plot, albeit an empty one).

**Comment by tobac** [comment]
Silly me. One can just use the generic plot() function, it seems. Is this the preferred way?

**Comment by AlexChristensen** [comment]
Hi @tobac,

Yes, you can just use `plot()`, which is the preferred way. I will be working on supplying more options (e.g., changing colors) soon.
