### ISSUE TITLE
Misscalculation in participation

### ISSUE THREAD

**Issue by jadenecke** [AlexChristensen/NetworkToolbox#6]
**Summary** <br />
Participation is calculated wrong (I think) in some specific cases. When there are as many communities as nodes within a fully connected network, the participation coefficient should be equal for every node.

<br />

**Reproduce** <br />
```
n <- 10  #try n = 9 and everything is as expected
m <- matrix(1, n, n)
diag(m) <- 0
com <- letters[seq(n)]
participation(m, com)

```

<br />

**NetworkToolbox Version** <br />
NetworkToolbox [1.4.2 ]

<br />

**Computer Specifications** <br />
Operating system: Windows

<br />

**Comment by AlexChristensen** [comment]
Thanks for catching this bug. It should now be fixed (see https://github.com/AlexChristensen/NetworkToolbox/commit/5b9bfd3a6640a506566e2ff89f975d3f18f0c87f)

When communities were > 10 and characters, then only 9 communities were used. Communities are made to be numeric to ensure proper estimation
