### ISSUE TITLE
Bugs and Errors

### ISSUE THREAD

**Issue by dazhwu** [AlexChristensen/NetworkToolbox#8]
Hi,

Around line 176 in depend.R, there is a block of code:

    for(h in 1:j)
        diag(parmat[,,h])<-1

In Equation 2 on Kenett et al 2010 ("Dominating Clasp of the Financial Sector Revealed by
Partial Correlation Analysis of the Stock Market"),  d(X,Y : Z) is defined as rou(X,Y) - rou(X,Y : Z). Then if X==Y, d is supposed to be zero, not 1.

Please correct me if I am wrong.

**Comment by AlexChristensen** [comment]
Hi @dazhwu,

You're correct that the diagonal should be 0 and not 1.

Updating shortly

**Comment by AlexChristensen** [comment]
Closing with fix https://github.com/AlexChristensen/NetworkToolbox/commit/914ff0b1eb6813a9d8153e3da4acc9edd393bb47
