### ISSUE TITLE
comm.str implementation

### ISSUE THREAD

**Issue by jadenecke** [AlexChristensen/NetworkToolbox#9]
**Summary** <br />
I am a bit unclear about the implementation of the community strength measure. Specifically the implementation looks like this:
```
rem <- which(comm == uniq[j])
sum(colSums(A[, rem])) #within
sum(colSums(A[, -rem])) #between
```

Either my understanding of within/between is incorrect, or this implementation. This implementation calculates for:
Within community strength: Sum of all edges of all nodes within the community, regardless whether the edge goes to the same community or any other community.
Between community strength: Sum of all edges of all nodes not belonging to the community, regardless whether the edge goes to the same community or any other community.

This method implies e.g. that the between community strength is equal to the sum of all other within community strengths. Or otherwise stated: between strength = strength - within strength
```
A <- TMFG(neoOpen, normal = FALSE)$A
comm <- igraph::walktrap.community(convert2igraph(abs(A)))$membership
within.ns <- comm.str(A, comm, measure = "within")
between.ns <- comm.str(A, comm, measure = "between")
sum.deg <- sum(strength(A, absolute = FALSE))
sum.deg - within.ns
#       1       2       3       4       5       6 
# 118.330 118.401 119.136 127.551 138.379 138.853 
between.ns 
#       1       2       3       4       5       6 
# 118.329 118.400 119.135 127.550 138.378 138.852 

```
<br />

**Suggestion** <br />
My understanding of within/between community strength is the following:
Within community strength: Sum of edges between all nodes belonging to the same community
Between community strength: Sum of edges going to nodes not belonging to the given community over all nodes belonging to the same community.
Therefore, in my understanding, the correct implementation would be 
```
rem <- which(comm == uniq[j])
sum(colSums(A[rem, rem])) #within
sum(colSums(A[-rem, rem])) #between
```

I might be completely mistaking here by my understanding, but I have also unfortunately not found a credible reference for the definition of the community strength. 
<br />

**NetworkToolbox Version** <br />
NetworkToolbox [1.4.3]

<br />

**Comment by AlexChristensen** [comment]
Hi @jadenecke,

This is a bug. Thanks for pointing it out to me.
